os: 
    - osx
osx_image: xcode12.5
language: cpp
compiler: g++
script:
    - export HOMEBREW_CORE_GIT_REMOTE="https://github.com/aaronliu0130/homebrew-core.git"
    - brew install --build-from-source tiv
    - brew test tiv
    - brew audit --new-formula tiv
